name: flutter_azure_event_hubs
description: Microsoft Azure Event Hubs NodeJs client wrapper for use in Flutter
version: 1.0.0
homepage: https://github.com/devops-damm-es/flutter-azure-event-hubs
repository: https://github.com/devops-damm-es/flutter-azure-event-hubs

publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  js: 0.6.3
  interactive_webview:
    git:
      url: https://github.com/devops-damm-es/flutter_hidden_webview.git
      ref: master
  kiwi: 3.0.0
  uuid: 3.0.6
  date_time_format: 2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/js/app.js