import 'package:flutter_azure_event_hubs/Infrastructure/Repositories/IClientSecretCredentialRepositoryService.dart';

abstract class IClientSecretCredentialDomainService {
  IClientSecretCredentialRepositoryService get repositoryService;
}
